spring:
  application:
    name=MaasService
  profiles:
    active: dev # prod or dev
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false  # 在log中顯示SQL語句  t:顯示  f:不顯示
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=maas

  doc:
    swagger-ui:
      path: /swagger-ui
      tagsSorter: alpha  # http://localhost:8080/MaasService/swagger-ui/index.html
    api-docs:
      path: /rest-api-docs
server:
  swagger:
    url: http://localhost:8080/MaasService
  servlet:
    context-path: /MaasService

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000